//package mscpcr.project.MSCPCR.entities;
//
//import java.util.Date;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//
//import org.hibernate.annotations.OnDelete;
//import org.hibernate.annotations.OnDeleteAction;
//
//import com.fasterxml.jackson.annotation.JsonIgnore;
//
//import lombok.Data;
//
//@Entity
//@Data
//@Table(name="dcpu_complaint_t")
//public class DCPUComplaint {
//	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Column(name ="complaint_no", nullable=false, unique=true)
//	private String complaint_no;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "district_code", nullable = false)
//	@OnDelete(action = OnDeleteAction.CASCADE)
//	@JsonIgnore
//	private District district;
//	
//	@Temporal(TemporalType.DATE)
//	@Column(name ="date_of_complaint", nullable=false, updatable=false) //auto generated by system
//	private Date date_of_complaint;
//	
//	@Temporal(TemporalType.DATE)
//	@Column(name ="date_of_receipt", nullable=false, updatable=false)
//	private Date date_of_receipt;
//	
//	@Column(name ="name_of_child", length=100, nullable=false, updatable=true)
//	private String name_of_child;
//	
//	@Column(name ="age_of_child", nullable=false, updatable=true)
//	private Integer age_of_child;
//	
//	@Column(name ="gender", nullable=false, updatable=true)// M=Male, F=female, O=Other
//	private Character gender;
//	
//	@Column(name ="complain_made_by", nullable=false, updatable=true)
//	private String complain_made_by;
//	
//	@Column(name ="contact_no", nullable=false, updatable=true)
//	private Integer contact_no;
//	
//	@Column(name ="case_summary", nullable=false, updatable=true)
//	private String case_summary;
//	
//	@Column(name ="place_of_incident", nullable=false, updatable=true)
//	private String place_of_incident;
//	
//	@Column(name ="accused_relationship_with_child", nullable=false, updatable=true)
//	private String accused_relationship_with_child;
//	
//	@Column(name ="disability", nullable=false, updatable=true)
//	private Character disability;
//	
//	@Column(name ="type_of_disability", nullable=false, updatable=true)
//	private String type_of_disability;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "caseType_Id", nullable = false, updatable=true)
//	@OnDelete(action = OnDeleteAction.CASCADE)
//	@JsonIgnore
//	private CaseType caseType;
//	
//	@Column(name ="case_progress", nullable=false, updatable=true) //D=Disposal, US=Under Surveillance, TR=Transfer
//	private Character case_progress;
//	
//	@Temporal(TemporalType.DATE)
//	@Column(name ="date_of_disposal", nullable=false, updatable=true) //auto generated by system
//	private Date date_of_disposal;
//	
//	@Column(name ="additional_info", nullable=false, updatable=true)
//	private String additional_info;
//	
//	@Column(name ="dcpu_remark", nullable=false, updatable=true)
//	private String dcpu_remark;
//	
//	
//	
//}
