//package mscpcr.project.MSCPCR.entities;
//
//import java.util.Date;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToOne;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//
//import org.hibernate.annotations.OnDelete;
//import org.hibernate.annotations.OnDeleteAction;
//
//import com.fasterxml.jackson.annotation.JsonIgnore;
//
//import lombok.Data;
//
//@Entity
//@Data
//@Table(name="police_FIR_t")
//public class PoliceFIR {
//	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Column(name ="police_FIR_no", nullable=false, unique=true)
//	private String police_FIR_no;
//	
//	@OneToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "complaint_no", nullable = false)
//	@OnDelete(action = OnDeleteAction.CASCADE)
//	@JsonIgnore
//	private DCPUwithPolice complaint;
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "district_code", nullable = false)
//	@OnDelete(action = OnDeleteAction.CASCADE)
//	@JsonIgnore
//	private District district;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "police_code", nullable = false)
//	@OnDelete(action = OnDeleteAction.CASCADE)
//	@JsonIgnore
//	private PoliceStation police_code;
//	
//	@Column(name ="FIR_no_with_section_of_law", nullable=false, updatable=true)
//	private String FIR_no_with_section_of_law;
//	
//	@Temporal(TemporalType.DATE)
//	@Column(name ="date_of_FIR", nullable=false, updatable=false) //auto generated by system
//	private Date date_of_FIR;
//	
//	@Temporal(TemporalType.DATE)
//	@Column(name ="date_of_medical_examination", nullable=false, updatable=false)
//	private Date date_of_medical_examination;
//	
//	@Column(name ="referred_to_CWC", nullable=false, updatable=true)
//	private String referred_to_CWC;
//	
//	@Column(name ="time_taken_to_file_chargeSheet", nullable=false, updatable=true)
//	private Integer time_taken_to_file_chargeSheet;
//	
//	@Column(name ="case_status", nullable=false, updatable=true)
//	private String case_status; 
//	
//	@Column(name ="police_remark", nullable=false, updatable=true)
//	private String police_remark;
//}
